### ISSUE TITLE
How to remove the use-query cache in react app?

### ISSUE THREAD

**Issue by mateus-melo0217** [mateus-melo0217/inxpress-shipment#4]
In general, the use-query library has its' cache and it is bothering us when we fetch the data with it.
How to deal with this?

**Comment by alerom114** [comment]
The possible way is to use the invalidate timeout or cache_time with 0.

**Comment by mateus-melo0217** [comment]
Which one is better?

**Comment by alerom114** [comment]
I think it is to use the invalidate timeout.

**Comment by mateus-melo0217** [comment]
thank you.
